version: '3'
services:
  mycat:
    build: .
    container_name: mycat
    ports:
      - "8066:8066"
      - "9066:9066"
    ulimits:
      nproc: 65535
    hostname: mycat
#    mem_limit: 1024m
    restart: always
